[package]
name = "image-compressor"
version = "0.0.1"
edition = "2021"
authors = ["reloginn <hexeo.dev@gmail.com>"]

[dependencies]
webp = "0.2.2"
image = "0.24.0"
clap = "2.33.4"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
